# Generated by Django 2.2.2 on 2019-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='uploaded_model')),
                ('discription', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uploaded media file history',
                'verbose_name_plural': 'Uploaded media file history',
                'ordering': ['created'],
            },
        ),
    ]
